MainWidget:

<MainWidget>:
    AnchorLayout:
        canvas:
            Color:
                rgb: 1, 1, 1
            Rectangle:
                size: root.width * .15, root.height
        size_hint: None, 1
        width: root.width * .15
        HamburgerMenuToggleButton:
            size_hint: None, None
            width: "90dp"
            height: "90dp"
        NavigationMenu:
            canvas:
                Color:
                    rgb: 1, 1, 0
                Line:
                    points: self.width, 0, self.width, root.height
                    width: 2
            anchor_x: "center"
            anchor_y: "center"
            size_hint: None, None
            width: root.width * .15
            height: root.height
            orientation: "vertical"
            MainMenuLink:
                color: 0, 0, 0
                font_size: "15dp"
            MySchedulesLink:
                color: 0, 0, 0
                font_size: "15dp"
            MyActivitiesLink:
                color: 0, 0, 0
                font_size: "15dp"
    RelativeLayout:
        size_hint: None, 1
        width: root.width * .8
