MainWidget:

<MainWidget>:
    LeftSideLayout:
        NavigationMenu:
            MainMenuLink:
            MySchedulesLink:
            MyActivitiesLink:
        # HamburgerMenuToggleButton:
    MainLayout:
        MainHeader:
        HeaderSubtext:
        AddingButtonBox:
            AddingButton:
                AddingButtonPlus:
            AddingDescription:
            AddingLabel: